In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
print(a.transpose())

[1 2 3 4]


In [3]:
A = np.array([1,2,3,4])
A_t = A[:, np.newaxis]
print(A)
print(A_t)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


In [4]:
print(a.T)

[1 2 3 4]


In [5]:
print(A.T)

[1 2 3 4]


In [13]:
a = np.array([[1,2,3,4]])

In [14]:
print(a.T)

[[1]
 [2]
 [3]
 [4]]


In [10]:
A = np.array([[2,3,4,5]]).T

In [15]:
print(A+a)

[[3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]


In [12]:
print(3*a)

[[ 3]
 [ 6]
 [ 9]
 [12]]


In [16]:
b = a.T
print(b*A)

[[ 2]
 [ 6]
 [12]
 [20]]


In [17]:
print(a*A)

[[ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]]


In [18]:
print(A*a)

[[ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]]


In [19]:
print(np.dot(a,A))

[[40]]


In [22]:
print(np.dot(A,a))

[[ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]]


In [23]:
print(np,dot(A.T,a))

NameError: name 'dot' is not defined

In [24]:
print(np.cross(A,a))

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [25]:
u = np.array([3,5])
v = np.array([1,4])
print(np.cross(u,v))

7


In [26]:
u = np.array([1,2,3])
v = np.array([2,3,4])
print(np.cross(u,v))

[-1  2 -1]
